### PR TITLE
Fix ObservableAsPropertyHelper guideline

### LINKED ISSUE #7: Copy-paste issue
In the "Prefer Observable Property Helpers to setting properties explicitly" section, the "Don't" part is copies from the previous section and not changed, has nothing to do with "Do" in this section.

### PR DESCRIPTION
**Pull request by Hinidu**
Make code in Do and Don't sections more related to each other.
Closes #7.

### CODE REVIEW

**Comment by Hinidu** [comment]
Is there something that I should do to speed up the merge?

**Comment by shiftkey** [comment]
hey @haacked can you :eyes: over this change? (I don't have write access)

**Comment by Haacked** [comment]
selfie-0

**Comment by Hinidu** [comment]
Thank you @Haacked and @shiftkey!

**Pull request merged**
